FROM maven:3.6.0-jdk-8-alpine AS build 
WORKDIR /app
COPY src /app  
COPY pom.xml /app
RUN cd /app && mvn clean package

FROM openjdk:8-jdk-alpine AS final-build
RUN adduser -D configserver
USER configserver
COPY --from=build /app/target/config-server-*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]